# Generated by Django 4.2.7 on 2023-11-21 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField(max_length=400)),
                ('delay', models.IntegerField(default=10)),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 18, 36, 10, 369513))),
            ],
        ),
    ]
