# Generated by Django 4.2.7 on 2023-11-21 18:37

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 11, 21, 18, 37, 18, 268877, tzinfo=datetime.timezone.utc)),
        ),
    ]
