# Generated by Django 4.2.7 on 2023-11-21 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
